### ISSUE TITLE
As there are not many developers around (yet?), input of everybody is appreciated.

### ISSUE THREAD

**Issue by Yummy121** [gosub-io/gosub-engine#161]
As there are not many developers around (yet?), input of everybody is appreciated. 

I have set up a mattermost server for testing at [https:;//chat.developer.gosub.io](https:;//chat.developer.gosub.io), to check if this is a viable option. If not, we can always check other systems. I have heard good stories about mattermost, but i have no experience with matrix. It might be an alternative as well, but we have to chose something.

_Originally posted by @jaytaph in https://github.com/gosub-browser/gosub-engine/discussions/75#discussioncomment-7190330_

**Comment by Kiyoshika** [comment]
?
