### ISSUE TITLE
Incorporate CSSOM into RenderTree

### ISSUE THREAD

**Issue by Kiyoshika** [gosub-io/gosub-engine#292]
This is more long term since the CSSOM doesn't exist yet, but when it does, need to leverage it to compute some of the styles/manipulate the box layout

**Comment by jaytaph** [comment]
I'm currently busy with the implementation of the css3 parser.  We have the "general parser" which is the one @neuodev has written, but it needs to have more specific parsers on top. For instance, the selector parser which understands how selectors are made up. There are a few more parsers we need to setup depending on the different css modules we support (we should support pretty much all of them as a browser).

So, at this point we have a semi-working AST which can be used for the CSSOM interface, but we still need to implement more.

**Comment by jaytaph** [comment]
We currently have a style calculator which can calculate the CSS properties per document node. This is the first step of the rendering pipeline which outputs the render tree

**Comment by jaytaph** [comment]
This is pretty much implemented in the new style CSS system
