### ISSUE TITLE
Revert `mod.rs` files

### ISSUE THREAD

**Issue by Kiyoshika** [gosub-io/gosub-engine#296]
From PR #268 we (accidentally) introduced `mod.rs` files again...

we've gone back and forth multiple times about which convention to use and it seems our project prefers the other style of having `module_name.rs` and a `module_name/` directory (if necessary) instead of `mod.rs` files

I think we should make a note of this in our contribution guidelines as this is now the second time this has happened :P (and likely will happen more in the future unless we make people aware)

**Comment by jaytaph** [comment]
it would be nice to have contribution guidelines. Would you like to take ownership of this and try to setup an initial one?

**Comment by Sharktheone** [comment]
I think, the reason was, because the mod.rs file was empty. I mentioned it in the PR, but i think, no one has seen it because the following messages were too big.

**Comment by Kiyoshika** [comment]
> it would be nice to have contribution guidelines. Would you like to take ownership of this and try to setup an initial one?

Yeah I can put together an initial one

**Comment by jaytaph** [comment]
@Kiyoshika I think you have created some? I only don't know where there are :-)

**Comment by Sharktheone** [comment]
What's the status of this? Should I make a PR to rename the `mod.rs` files again? I'm not really good at writing things like contribution guidelines, so I probably shouldn't be the person to write them.

**Comment by jaytaph** [comment]
i'm not sure where they are. I've seen some though,.. somewhere... :-)  @Kiyoshika might know where

**Comment by jaytaph** [comment]
so, according to this contribution guide, we should use the non-mod.rs version. So yes, we should revert them back.

**Comment by Sharktheone** [comment]
> ow.. this is really stupid from me... it is just in the https://github.com/gosub-browser/gosub-engine/blob/main/CONTRIBUTING.md
> 
> :-)

oh, also completely missed that...
