### ISSUE TITLE
Move "global" tests from ./tests to the correct crates

### ISSUE THREAD

**Issue by jaytaph** [gosub-io/gosub-engine#445]
There are a few tests in the root directory `./tests` dir. These should be moved to the correct crate found in `./crates`.

**Comment by kaigidwani** [comment]
Hello! I'm new to all of this and looking for a contribution I may be able to make to this project, for an assignment in my class I'm taking on FOSS. I was interested in taking this on, but I am a bit unclear on it. I am unsure specifically which files need to get moved out of the tests folder, and where they should be put in the crates folder. I've also put this message on the Zulip.

**Comment by Sharktheone** [comment]
Completed in #457
