### ISSUE TITLE
Scrolling a page that isn't 100vh high, causes it to stuck at the bottom after the first scroll

### ISSUE THREAD

**Issue by Sharktheone** [gosub-io/gosub-engine#618]
Pre scroll:
![image](https://github.com/user-attachments/assets/5e07df6f-6898-4dc1-b76d-afabd95566ae)
After scroll:
![image](https://github.com/user-attachments/assets/f42e6ea4-db04-448b-bef7-406fa8d753fe)

**Comment by DynamiteC** [comment]
@Sharktheone, Can I work on this?

**Comment by Sharktheone** [comment]
Sure, just do it if you live.

**Comment by jaytaph** [comment]
@DynamiteC If you need any help, we have a zulip chat on https://chat.developer.gosub.io
